name: catkin_build

on: [push]

defaults:
  run:
    shell: bash
jobs:
  catkin_build:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    container:
      image: ros:noetic
    steps:
      - run: apt-get update && apt-get install -y git
      - run: apt-get install -y python3-pip ros-noetic-catkin python3-catkin-tools

      - uses: actions/checkout@v2
        with:
          path: catkin_ws/src/dronecan_communicator
          submodules: recursive

      - name: Install requirements
        run: |
          cd catkin_ws/src/dronecan_communicator
          ./scripts/install_requirements.sh
          ./scripts/install_libuavcan.sh

      # - name: Generate custom dsdl
      #   run: |
      #     cd catkin_ws/src/dronecan_communicator
      #     ./scripts/compile_dsdl.sh

      - name: catkin build
        run: |
          source /opt/ros/$ROS_DISTRO/setup.bash
          cd catkin_ws
          catkin build
