name: catkin_build

on: [push]

defaults:
  run:
    shell: bash
jobs:
  catkin_build:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    container:
      image: ros:noetic
    steps:
      - name: Handle issue with actions/checkout when Git version is less than 2.18
        run: apt-get update && apt-get install -y git

      - uses: actions/checkout@v4
        with:
          path: catkin_ws/src/dronecan_communicator
          submodules: recursive

      - name: Install requirements
        run: ./catkin_ws/src/dronecan_communicator/scripts/install.sh

      - name: catkin build
        run: source /opt/ros/$ROS_DISTRO/setup.bash && cd catkin_ws && catkin build
